# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4d6fcc14c23048133c60bf448a7e305b018379afd46be972f4b83487a406ca3096fb0a6eb339a41e957a5fb73483e9048f487fe3ee4491aec750efa278cfd0

test:
  secret_key_base: 16f23682a14ff3885f7fe9ac568ac615718f3b75a031d3fd49201787785ca5dd1563011d029cf1a40ad965f3234b2700e30d429fcec16cf57461b8ed32b0766f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
